access_key = "**"
secret_access_key = "**"
FLUX_API_KEY = "**"

[huggingface]
token = "**"


[gemini]
api_key = "AIzaSyCY8ZrvoRHxADqqfU8JybLJu1D1QKxiX-o"


omdb_apikey = '8d8b1a2d'
openai_apikey = 'org-IVd132dKH8iZEpkWfOXDSMJ9' 
slack_webhook_url = '**'