access_key = "**"
secret_access_key = "**"
FLUX_API_KEY = "**"

[huggingface]
token = "**"

[gemini]
api_key = "**"


omdb_apikey = '8d8b1a2d'
openai_apikey = 'org-IVd132dKH8iZEpkWfOXDSMJ9' 
slack_webhook_url = '**'